### PR TITLE
Update nokogiri dependency to patch critical vulnerability

### PR DESCRIPTION
**Pull request by npch**
This is the suggested change to remove nokogiri vulnerabilities.

### CODE REVIEW

**Comment by mkuzak** [comment]
thanks @npch, did you check if that builds after this single change, does not break anything else?

**Comment by npch** [comment]
Hi @mkuzak build works on my machine, however I noticed that on the Recommendations page, there seems to be an issue with formatting after the first recommendation, see screenshot below:

image

Note: this formatting issue also seems to happen when I build the site locally using the master branch.

**Comment by rajido** [comment]
I am merging this pull request. I did run locally and it seems everything is fine except the headers for the recommendations page. As @npch mentioned the formatting problem happens in the branch and in the master. I will revert the pull request if the problems with the headers show in the pages generated by GitHub.

**Comment by mkuzak** [comment]
all looks good to me renedered on GitHub, thank you

**Pull request merged**
